%%
%加噪声
I=rgb2gray(imread('images.jpg'));%读取图像
Ga=imnoise(I,'gaussian',0,0.05);%加入均值为0，方差为0.005的高斯噪声
Salt=imnoise(I,'salt & pepper',0.05);%加入椒盐噪声
Po=imnoise(I,'poisson');%加入泊松噪声
figure(1);
subplot(221);imshow(I);title('原始图像');
subplot(222);imshow(Ga);title('加入高斯噪声');
subplot(223);imshow(Salt);title('加入椒盐噪声');
subplot(224);imshow(Po);title('加入泊松噪声');
%%
%空间去噪——中值滤波
figure(2);
K1=medfilt2(Ga,[3,3]);%中值滤波
subplot(131);imshow(K1);title('高斯噪声中值滤波');
K2=medfilt2(Salt,[3,3]);
subplot(132);imshow(K2);title('椒盐噪声中值滤波');
K3=medfilt2(Po,[3,3]);
subplot(133);imshow(K3);title('泊松噪声中值滤波');
figure(3);%中值滤波
pgr1=plotbar(I(:));    
subplot(221);bar(pgr1);title('原图像的直方图');  
pgr2=plotbar(K1(:));    
subplot(222);bar(pgr2);title('高斯噪声中值滤波');     
pgr3=plotbar(K2(:));    
subplot(223);bar(pgr3);title('椒盐噪声中值滤波');
pgr3=plotbar(K3(:));    
subplot(224);bar(pgr3);title('泊松噪声中值滤波');
%%
%空间去噪——均值滤波，模板尺寸为3
figure(4);
K1=filter2(fspecial('average',3),Ga)/255;
subplot(131);imshow(K1);title('高斯噪声均值滤波');
K2=filter2(fspecial('average',3),Salt)/255;
subplot(132);imshow(K2);title('椒盐噪声均值滤波');
K3=filter2(fspecial('average',3),Po)/255;
subplot(133);imshow(K3);title('泊松噪声均值滤波');
figure(5);%中值滤波
pgr1=plotbar(I(:));    
subplot(221);bar(pgr1);title('原图像的直方图');  
pgr2=plotbar(K1(:));    
subplot(222);bar(pgr2);title('高斯噪声均值滤波');     
pgr3=plotbar(K2(:));    
subplot(223);bar(pgr3);title('椒盐噪声均值滤波');
pgr3=plotbar(K3(:));    
subplot(224);bar(pgr3);title('泊松噪声均值滤波');
%%
%维纳滤波
figure(6);
K1=wiener2(Ga,[3,3]);
subplot(131);imshow(K1);title('高斯噪声维纳滤波');
K2=wiener2(Salt,[3,3]);
subplot(132);imshow(K2);title('椒盐噪声维纳滤波');
K3=wiener2(Po,[3,3]);
subplot(133);imshow(K3);title('泊松噪声维纳滤波');
%%
%频率域降噪
figure(7);
E12=fftdeletenoise(Ga);
subplot(131);imshow(E12);title('fft处理高斯噪声');
E22=fftdeletenoise(Salt);
subplot(132);imshow(E22);title('fft处理椒盐噪声');
E32=fftdeletenoise(Po);
subplot(133);imshow(E32);title('fft处理泊松噪声'); 
figure(8);
pgr1=plotbar(I(:));    
subplot(221);bar(pgr1);title('原图像的直方图');  
pgr2=plotbar(E12(:));    
subplot(222);bar(pgr2);title('高斯噪声fft降噪');     
pgr3=plotbar(E22(:));    
subplot(223);bar(pgr3);title('椒盐噪声fft降噪');
pgr3=plotbar(E32(:));    
subplot(224);bar(pgr3);title('泊松噪声fft降噪');  